config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root 'kittens#index'
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  
  def new 
    @kitten = Kitten.new
  end 

  def create 
    @kitten = Kitten.new(kitten_params)
    if @kitten.save 
      flash[:success] = "Kitten successfully saved"
      redirect_to root_url
    else 
      render 'new'
    end 
  end

  def index 
    @kitten = Kitten.all
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end 
  end 

  def show 
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end 
  end 

  def edit
    @kitten = Kitten.find(params[:id])
  end 

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "Kitten successfully edited"
      redirect_to @kitten 
    else 
      render 'edit'
    end 
  end 

  def destroy
    @kitten = Kitten.find(params[:id])
    if @kitten.destroy
      flash[:success] = "Kitten Removed"
      redirect_to root_url
    end 
  end 

  private 

  def kitten_params 
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%=form_for(@kitten) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %></br>
  <%= f.label :age %>
  <%= f.text_field :age, class: 'form-control' %></br>
  <%= f.label :cuteness %>
  <%= f.text_field :cuteness, class: 'form-control' %></br>
  <%= f.label :softness %>
  <%= f.text_field :softness, class: 'form-control' %></br>
  <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
<% end %>

app/views/kittens/edit.html.erb
<% provide(:button_text, "Save Changes") %>
<h1>Edit kitten info</h1>
<%= render 'form' %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>
<% @kitten.each do |kitten| %>
  <ul>Name: <%= kitten.name %> 
    <li>Age <%= kitten.age %></li>
    <li>Cuteness <%= kitten.cuteness %></li>
    <li>Softness <%= kitten.softness %></li>
    <li><%= link_to "Remove", kitten_path(kitten.id), method: :delete,
                                      data: { confirm: "You sure?" }%></li>
  </ul>
<% end %>

app/views/kittens/new.html.erb
<% provide(:button_text, 'Create') %>
<h1>New Kitten</h1>
<%= render 'form' %>

app/views/kittens/show.html.erb
<h1>Kitten Info</h1>
<ul>Name: <%= @kitten.name %> 
  <li>Age <%= @kitten.age %></li>
  <li>Cuteness <%= @kitten.cuteness %></li>
  <li>Softness <%= @kitten.softness %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to "Home", root_url%>
  <%= link_to "New", new_kitten_path %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
    <%= yield %>
  </body>
</html>